#!/usr/bin/env python3
"""
CHOMBEZA - WAF Detection Plugin
Detects Web Application Firewalls and their types
"""

import re
import logging
from typing import Dict, List, Any

logger = logging.getLogger("CHOMBEZA.Plugin.WAFDetector")

class WAFDetectorPlugin:
    """Plugin to detect Web Application Firewalls"""
    
    plugin_metadata = {
        "name": "WAF Detector",
        "version": "1.0.0",
        "author": "CHOMBEZA Team",
        "description": "Detects WAF presence and identifies WAF type",
        "vulnerabilities": ["waf_detection"]
    }
    
    # WAF signatures
    WAF_SIGNATURES = [
        {
            "name": "Cloudflare",
            "headers": ["cf-ray", "cf-cache-status"],
            "cookies": ["__cfduid"],
            "response": r"cloudflare-nginx|cloudflare",
            "confidence": 90
        },
        {
            "name": "AWS WAF",
            "headers": ["x-amzn-RequestId", "x-amz-cf-id"],
            "response": r"Request blocked.*AWS WAF",
            "confidence": 85
        },
        {
            "name": "Akamai",
            "headers": ["x-akamai-", "x-akamai-transformed"],
            "response": r"akamai|Akamaighost",
            "confidence": 85
        },
        {
            "name": "Imperva",
            "headers": ["x-iinfo", "x-cdn"],
            "cookies": ["incap_ses_", "visid_incap_"],
            "response": r"Imperva|Incapsula",
            "confidence": 85
        },
        {
            "name": "F5 BIG-IP",
            "headers": ["x-wa-info", "x-asbd-id"],
            "cookies": ["LastMRH_Session", "MRHSession"],
            "response": r"BIG-IP|F5",
            "confidence": 80
        },
        {
            "name": "ModSecurity",
            "headers": ["x-mod-security"],
            "response": r"ModSecurity|web application firewall",
            "confidence": 75
        },
        {
            "name": "Sucuri",
            "headers": ["x-sucuri-id", "x-sucuri-cache"],
            "response": r"Sucuri|CloudProxy",
            "confidence": 80
        },
        {
            "name": "Wordfence",
            "headers": [],
            "cookies": ["wfvt_", "wordfence_verifiedHuman"],
            "response": r"Wordfence|Generated by Wordfence",
            "confidence": 85
        },
        {
            "name": "Barracuda",
            "headers": ["x-barracuda"],
            "response": r"Barracuda",
            "confidence": 80
        },
        {
            "name": "Citrix Netscaler",
            "headers": ["x-netscaler"],
            "cookies": ["NSC_"],
            "confidence": 75
        }
    ]
    
    def __init__(self):
        self.enabled = True
        self.detected_wafs = []
    
    def post_request(self, scanner, response: Any, task: Dict) -> None:
        """Check response for WAF signatures"""
        if not response or not hasattr(response, 'headers'):
            return
        
        headers = response.headers
        content = response.text if hasattr(response, 'text') else ''
        
        for waf in self.WAF_SIGNATURES:
            # Check headers
            header_match = any(
                any(h.lower().startswith(pattern.lower()) for h in headers.keys())
                for pattern in waf.get('headers', [])
            )
            
            # Check cookies
            cookie_match = any(
                any(c.startswith(pattern) for c in headers.get('Set-Cookie', '').split(';'))
                for pattern in waf.get('cookies', [])
            ) if 'Set-Cookie' in headers else False
            
            # Check response body
            response_match = False
            if 'response' in waf:
                response_match = bool(re.search(waf['response'], content, re.I))
            
            if header_match or cookie_match or response_match:
                waf_info = {
                    "name": waf["name"],
                    "confidence": waf["confidence"],
                    "evidence": {
                        "headers": header_match,
                        "cookies": cookie_match,
                        "response": response_match
                    }
                }
                
                if waf_info not in self.detected_wafs:
                    self.detected_wafs.append(waf_info)
                    logger.info(f"🔥 Detected WAF: {waf['name']} (confidence: {waf['confidence']}%)")
    
    def post_scan(self, scanner, results: Dict) -> None:
        """Add WAF detection findings to scan results"""
        if not self.detected_wafs:
            return
        
        # Create finding for each detected WAF
        for waf in self.detected_wafs:
            finding = {
                "name": f"WAF Detected: {waf['name']}",
                "severity": "info",
                "url": scanner.target,
                "description": f"Web Application Firewall detected: {waf['name']}",
                "evidence": f"Detected with {waf['confidence']}% confidence based on headers/cookies/response patterns",
                "recommendation": "Be aware of WAF presence when crafting payloads. Consider WAF evasion techniques.",
                "confidence": waf['confidence'],
                "cwe_id": "CWE-000",
                "category": "Configuration",
                "waf_name": waf['name'],
                "detection_method": waf['evidence']
            }
            
            # Use scanner's internal method to add vulnerability
            if hasattr(scanner, '_add_vulnerability'):
                scanner._add_vulnerability(**finding)
    
    def pre_request(self, scanner, task: Dict) -> Dict:
        """Add WAF evasion headers if configured"""
        if scanner.config.get("evasion", False) and self.detected_wafs:
            # Add random delays between requests
            import time
            import random
            time.sleep(random.uniform(0.5, 2.0))
            
            # Rotate user agents
            user_agents = [
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15",
                "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1"
            ]
            
            if 'headers' not in task:
                task['headers'] = {}
            
            task['headers']['User-Agent'] = random.choice(user_agents)
        
        return task